[main]
docker_bin = "/usr/bin/docker"
default_command_args = [
    { command_name = "up", command_args = [
        "-d",
        "--remove-orphans",
    ] },
]

[[collections]]
alias = "mssql"
description = "Runs MSSQL Server\nUsername: sa\nPassword: ZsQPJst6pcZQaLHt"
compose_files = ["/home/mhl/compose/db/mssql/docker-compose.yml"]

[[collections]]
alias = "mysql"
description = "Runs MySQL Server\nUsername: root\nPassword: rootie"
compose_files = ["/home/mhl/compose/db/mysql/docker-compose.yml"]

[[collections]]
alias = "postgres"
description = "Runs Postgres Server\nDB Username: unicorn_user\nDB Password: magical_password\npgAdmin Username: pgadmin4@pgadmin.org\npgAdmin Password: admin"
enviroment_file = "/home/mhl/compose/db/postgresql/database.env"
compose_files = ["/home/mhl/compose/db/postgresql/docker-compose.yml"]

[[collections]]
alias = "cosmos"
description = "Runs Cosmos Emulator\nData Explorer: http://localhost:8081"
compose_files = ["/home/mhl/compose/cosmos/docker-compose.yml"]

[[collections]]
alias = "obs"
description = "Runs Observability cluster with Grafana\nGrafana url: http://localhost:3000\nGrafana Username: admin\nGrafana Password: admin"
compose_files = ["/home/mhl/compose/observability/docker-compose.yml"]

[[collections]]
alias = "aspire_dash"
description = "Run the Apsire dashboard standalone\nhttp://localhost:18888"
compose_files = ["/home/mhl/compose/aspire-dashboard/docker-compose.yml"]