apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\"traceid\":\"(\\w+)\""
          name: traceID
          # url will be interpreted as query for the datasource
          url: '$${__value.raw}'