apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo
    access: proxy
    basicAuth: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki' 
        spanStartTimeShift: 0
        spanEndTimeShift: 0
        tags: [{key: 'service.name', value: 'job'}, {key: 'spanId', value: 'SpanId'}, {key: 'traceId', value: 'TraceId'}]
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{$${__tags}} | json | line_format "[{{.level}}] {{.body}}"'
      # tracesToMetrics:
      #   datasourceUid: 'prom'
      #   spanStartTimeShift: '1h'
      #   spanEndTimeShift: '-1h'
      #   tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
      #   queries:
      #     - name: 'Sample query'
      #       query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
      # serviceMap:
      #   datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: 'loki'
      spanBar:
        type: 'Tag'
        tag: 'http.path'
